/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Apps */
        get: operations["list_apps_api_v1_apps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{app}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get App */
        get: operations["get_app_api_v1_apps__app__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{app}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get App Logs */
        get: operations["get_app_logs_api_v1_apps__app__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{app}/logs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream App Logs */
        get: operations["stream_app_logs_api_v1_apps__app__logs_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{app}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start App */
        post: operations["start_app_api_v1_apps__app__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{app}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop App */
        post: operations["stop_app_api_v1_apps__app__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{app}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart App */
        post: operations["restart_app_api_v1_apps__app__restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{app}/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Install App */
        post: operations["install_app_api_v1_apps__app__install_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{app}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remove App */
        post: operations["remove_app_api_v1_apps__app__remove_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{app}/reinstall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reinstall App */
        post: operations["reinstall_app_api_v1_apps__app__reinstall_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{app}/recreate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recreate App */
        post: operations["recreate_app_api_v1_apps__app__recreate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{app}/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Backup App */
        post: operations["backup_app_api_v1_apps__app__backup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{app}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get App History */
        get: operations["get_app_history_api_v1_apps__app__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{app}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get App Stats */
        get: operations["get_app_stats_api_v1_apps__app__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{app}/env": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get App Env */
        get: operations["get_app_env_api_v1_apps__app__env_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{app}/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get App Auth */
        get: operations["get_app_auth_api_v1_apps__app__auth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit */
        get: operations["list_audit_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List App Auth */
        get: operations["list_app_auth_api_v1_auth_apps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Auth */
        post: operations["bulk_auth_api_v1_auth_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Backups */
        get: operations["get_backups_api_v1_backups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Diagnostics */
        get: operations["run_diagnostics_api_v1_diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/rebuild-registries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebuild Registries */
        post: operations["rebuild_registries_api_v1_diagnostics_rebuild_registries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/cleanup-orphan-containers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cleanup Orphan Containers */
        post: operations["cleanup_orphan_containers_api_v1_diagnostics_cleanup_orphan_containers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/cleanup-dangling-volumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cleanup Dangling Volumes */
        post: operations["cleanup_dangling_volumes_api_v1_diagnostics_cleanup_dangling_volumes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Events */
        get: operations["job_events_api_v1_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_api_v1_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Read All */
        post: operations["read_all_api_v1_notifications_read_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark Read */
        patch: operations["mark_read_api_v1_notifications__notification_id__read_patch"];
        trace?: never;
    };
    "/api/v1/notifications/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notification Events */
        get: operations["notification_events_api_v1_notifications_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/security": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Security */
        get: operations["get_security_api_v1_security_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Security */
        patch: operations["update_security_api_v1_security_patch"];
        trace?: never;
    };
    "/api/v1/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Setup Status */
        get: operations["setup_status_api_v1_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Setup */
        post: operations["run_setup_api_v1_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_api_v1_system_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_api_v1_system_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get System Health */
        get: operations["get_system_health_api_v1_system_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Updates */
        get: operations["get_updates_api_v1_updates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertsCheck */
        AlertsCheck: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "warning";
            /**
             * Unread
             * @default 0
             */
            unread: number;
        };
        /** AppAuthOut */
        AppAuthOut: {
            /** Schema */
            schema: number;
            /** App */
            app: string;
            /** Auth */
            auth: string | null;
        };
        /** AppAuthSummary */
        AppAuthSummary: {
            /** App */
            app: string;
            /** Auth */
            auth: string | null;
        };
        /** AppDetailOut */
        AppDetailOut: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Available */
            available: boolean;
            /** Installed */
            installed: boolean;
            /**
             * Runtime Status
             * @enum {string}
             */
            runtime_status: "running" | "partial" | "stopped" | "unknown" | "not_installed";
            /** Healthy */
            healthy: boolean | null;
            /** Url */
            url: string | null;
            /** Image */
            image: string | null;
            /** Containers */
            containers: number;
            /** Warnings */
            warnings: string[];
            /** Container List */
            container_list: components["schemas"]["ContainerOut"][];
            ssddb: components["schemas"]["SsddbAppOut"] | null;
            registries: components["schemas"]["RegistriesOut"];
        };
        /** AppEnvOut */
        AppEnvOut: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** App */
            app: string;
            /** Variables */
            variables: components["schemas"]["AppEnvVarOut"][];
        };
        /** AppEnvVarOut */
        AppEnvVarOut: {
            /** Name */
            name: string;
            /** Value */
            value: string;
        };
        /** AppHistoryEvent */
        AppHistoryEvent: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "job" | "audit" | "notification" | "backup";
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Actor */
            actor?: string | null;
            /** Label */
            label: string;
            /** Result */
            result: string;
            /** Job Id */
            job_id?: number | null;
        };
        /** AppHistoryOut */
        AppHistoryOut: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** App */
            app: string;
            /** Events */
            events: components["schemas"]["AppHistoryEvent"][];
        };
        /** AppInstallRequest */
        AppInstallRequest: {
            /**
             * Auth
             * @enum {string}
             */
            auth: "aucune" | "basique" | "authelia" | "oauth" | "oauth2-proxy";
            /** Subdomain */
            subdomain?: string | null;
        };
        /** AppRemoveRequest */
        AppRemoveRequest: {
            /**
             * Delete Data
             * @default false
             */
            delete_data: boolean;
        };
        /** AppStateOut */
        AppStateOut: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Available */
            available: boolean;
            /** Installed */
            installed: boolean;
            /**
             * Runtime Status
             * @enum {string}
             */
            runtime_status: "running" | "partial" | "stopped" | "unknown" | "not_installed";
            /** Healthy */
            healthy: boolean | null;
            /** Url */
            url: string | null;
            /** Image */
            image: string | null;
            /** Containers */
            containers: number;
            /** Warnings */
            warnings: string[];
        };
        /** AppStatsOut */
        AppStatsOut: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** App */
            app: string;
            /** Containers */
            containers: components["schemas"]["ContainerStatsOut"][];
        };
        /** AuditEventOut */
        AuditEventOut: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Username */
            username: string | null;
            /** Action */
            action: string;
            /** Target */
            target: string | null;
            /** Status */
            status: string;
            /** Detail */
            detail: string | null;
        };
        /** AuthBulkRequest */
        AuthBulkRequest: {
            /** Apps */
            apps: string[];
            /**
             * Auth
             * @enum {string}
             */
            auth: "aucune" | "basique" | "authelia" | "oauth" | "oauth2-proxy";
        };
        /** BackupCheck */
        BackupCheck: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unknown";
            /** Last At */
            last_at?: string | null;
            /**
             * Count
             * @default 0
             */
            count: number;
        };
        /** BackupOut */
        BackupOut: {
            /** App */
            app: string;
            /** File */
            file: string;
            /** Size */
            size: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ConfigOut */
        ConfigOut: {
            /** Schema */
            schema: number;
            /** Config */
            config: {
                [key: string]: string | null;
            };
        };
        /** ContainerMetrics */
        ContainerMetrics: {
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Running
             * @default 0
             */
            running: number;
            /**
             * Healthy
             * @default 0
             */
            healthy: number;
            /**
             * Unhealthy
             * @default 0
             */
            unhealthy: number;
            /**
             * Stopped
             * @default 0
             */
            stopped: number;
        };
        /** ContainerOut */
        ContainerOut: {
            /** Name */
            name: string;
            /** Image */
            image: string | null;
            /** State */
            state: string;
            /** Health */
            health: string | null;
        };
        /** ContainerStatsOut */
        ContainerStatsOut: {
            /** Name */
            name: string;
            /** Cpu Percent */
            cpu_percent?: number | null;
            /** Memory Used Bytes */
            memory_used_bytes?: number | null;
            /** Memory Limit Bytes */
            memory_limit_bytes?: number | null;
            /** Memory Percent */
            memory_percent?: number | null;
        };
        /** DiagnosticsChecks */
        DiagnosticsChecks: {
            /** Missing Registries */
            missing_registries: string[];
            /** Orphan Containers */
            orphan_containers: string[];
            /** Dangling Volumes */
            dangling_volumes: number;
        };
        /** DiagnosticsOut */
        DiagnosticsOut: {
            /** Schema */
            schema: number;
            checks: components["schemas"]["DiagnosticsChecks"];
            /** Warnings */
            warnings: string[];
        };
        /** DiskMetric */
        DiskMetric: {
            /** Total Bytes */
            total_bytes?: number | null;
            /** Used Bytes */
            used_bytes?: number | null;
            /** Percent */
            percent?: number | null;
        };
        /** DnsCheck */
        DnsCheck: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "failed" | "unknown";
            /** Hostname */
            hostname?: string | null;
            /**
             * Addresses
             * @default []
             */
            addresses: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Docker */
            docker: boolean;
            /** Ssdv2 */
            ssdv2: boolean;
            /** Ssdv2Ctl */
            ssdv2ctl: boolean;
            /** Database */
            database: boolean;
        };
        /** HostMetricsOut */
        HostMetricsOut: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Cpu Percent */
            cpu_percent?: number | null;
            /** Cpu Count */
            cpu_count?: number | null;
            /** @default {} */
            memory: components["schemas"]["MemoryMetric"];
            /** @default {} */
            disk: components["schemas"]["DiskMetric"];
            /**
             * @default {
             *       "total": 0,
             *       "running": 0,
             *       "healthy": 0,
             *       "unhealthy": 0,
             *       "stopped": 0
             *     }
             */
            containers: components["schemas"]["ContainerMetrics"];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** HostSummary */
        HostSummary: {
            /** Hostname */
            hostname?: string | null;
            /** Os */
            os?: string | null;
            /** Kernel */
            kernel?: string | null;
            /** Architecture */
            architecture?: string | null;
            /** Cpus */
            cpus?: number | null;
            /** Memory Bytes */
            memory_bytes?: number | null;
            /** Server Version */
            server_version?: string | null;
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Target */
            target: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "success" | "failed" | "cancelled" | "interrupted";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Exit Code */
            exit_code: number | null;
            /** Message */
            message: string | null;
        };
        /** JobsCheck */
        JobsCheck: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Active
             * @default 0
             */
            active: number;
            /**
             * Failed Recent
             * @default 0
             */
            failed_recent: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LogsOut */
        LogsOut: {
            /** App */
            app: string;
            /** Container */
            container: string;
            /** Lines */
            lines: string[];
        };
        /** MemoryMetric */
        MemoryMetric: {
            /** Total Bytes */
            total_bytes?: number | null;
            /** Used Bytes */
            used_bytes?: number | null;
            /** Percent */
            percent?: number | null;
        };
        /** NotificationListOut */
        NotificationListOut: {
            /** Items */
            items: components["schemas"]["NotificationOut"][];
            /** Unread */
            unread: number;
        };
        /** NotificationOut */
        NotificationOut: {
            /** Id */
            id: number;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "success" | "warning" | "error";
            /** Title */
            title: string;
            /** Message */
            message: string | null;
            /** Source */
            source: string | null;
            /** Link */
            link: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Read At */
            read_at: string | null;
        };
        /** RegistriesOut */
        RegistriesOut: {
            /** Containers */
            containers: string[];
            /** Volumes */
            volumes: string[];
            /** Dns */
            dns: string[];
        };
        /** SecurityOut */
        SecurityOut: {
            /** Internal Auth */
            internal_auth: boolean;
        };
        /** SecurityUpdateRequest */
        SecurityUpdateRequest: {
            /** Internal Auth */
            internal_auth: boolean;
        };
        /** ServiceCheck */
        ServiceCheck: {
            /** Key */
            key: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "unknown";
            /** Detail */
            detail?: string | null;
        };
        /** SetupRequest */
        SetupRequest: {
            /** Token */
            token: string;
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Internal Auth
             * @default true
             */
            internal_auth: boolean;
            /**
             * Instance Name
             * @default SSDV2 WebUI
             */
            instance_name: string;
            /**
             * Notify Job Success
             * @default true
             */
            notify_job_success: boolean;
        };
        /** SetupStatusOut */
        SetupStatusOut: {
            /** Required */
            required: boolean;
            /** Token Required */
            token_required: boolean;
            /** Instance Name */
            instance_name: string;
        };
        /** SsddbAppOut */
        SsddbAppOut: {
            /** Status */
            status: number | null;
            /** Subdomain */
            subdomain: string | null;
            /** Port */
            port: number | null;
        };
        /** Ssdv2Summary */
        Ssdv2Summary: {
            /** Branch */
            branch?: string | null;
            /** Commit */
            commit?: string | null;
            /**
             * Apps Total
             * @default 0
             */
            apps_total: number;
            /**
             * Installed
             * @default 0
             */
            installed: number;
            /**
             * Running
             * @default 0
             */
            running: number;
            /**
             * Stopped
             * @default 0
             */
            stopped: number;
            /**
             * Unknown
             * @default 0
             */
            unknown: number;
            /**
             * Not Installed
             * @default 0
             */
            not_installed: number;
        };
        /** SystemHealthOut */
        SystemHealthOut: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Services */
            services: components["schemas"]["ServiceCheck"][];
            tls: components["schemas"]["TlsCheck"];
            dns: components["schemas"]["DnsCheck"];
            backups: components["schemas"]["BackupCheck"];
            jobs: components["schemas"]["JobsCheck"];
            alerts: components["schemas"]["AlertsCheck"];
        };
        /** SystemSummaryOut */
        SystemSummaryOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            host: components["schemas"]["HostSummary"];
            ssdv2: components["schemas"]["Ssdv2Summary"];
            /** Warnings */
            warnings: string[];
        };
        /** TlsCheck */
        TlsCheck: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "warning" | "unknown";
            /** Hostname */
            hostname?: string | null;
            /** Days Remaining */
            days_remaining?: number | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /** UpdateEntry */
        UpdateEntry: {
            /** App */
            app: string;
            /** Image */
            image: string;
            /** Current Digest */
            current_digest?: string | null;
            /** Available Digest */
            available_digest?: string | null;
            /**
             * Status
             * @default unknown
             * @enum {string}
             */
            status: "up_to_date" | "available" | "unknown";
        };
        /** UpdatesOut */
        UpdatesOut: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Entries */
            entries: components["schemas"]["UpdateEntry"][];
            /**
             * Available
             * @default 0
             */
            available: number;
        };
        /** UserOut */
        UserOut: {
            /** Username */
            username: string;
            /**
             * Internal Auth
             * @default true
             */
            internal_auth: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_apps_api_v1_apps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppStateOut"][];
                };
            };
        };
    };
    get_app_api_v1_apps__app__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_app_logs_api_v1_apps__app__logs_get: {
        parameters: {
            query?: {
                container?: string | null;
                lines?: number;
            };
            header?: never;
            path: {
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_app_logs_api_v1_apps__app__logs_stream_get: {
        parameters: {
            query?: {
                container?: string | null;
                lines?: number;
            };
            header?: never;
            path: {
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_app_api_v1_apps__app__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_app_api_v1_apps__app__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restart_app_api_v1_apps__app__restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    install_app_api_v1_apps__app__install_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppInstallRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_app_api_v1_apps__app__remove_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppRemoveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reinstall_app_api_v1_apps__app__reinstall_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recreate_app_api_v1_apps__app__recreate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backup_app_api_v1_apps__app__backup_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_app_history_api_v1_apps__app__history_get: {
        parameters: {
            query?: {
                kind?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppHistoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_app_stats_api_v1_apps__app__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppStatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_app_env_api_v1_apps__app__env_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppEnvOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_app_auth_api_v1_apps__app__auth_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppAuthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_api_v1_audit_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_app_auth_api_v1_auth_apps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppAuthSummary"][];
                };
            };
        };
    };
    bulk_auth_api_v1_auth_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthBulkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_backups_api_v1_backups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupOut"][];
                };
            };
        };
    };
    get_config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
        };
    };
    run_diagnostics_api_v1_diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsOut"];
                };
            };
        };
    };
    rebuild_registries_api_v1_diagnostics_rebuild_registries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
        };
    };
    cleanup_orphan_containers_api_v1_diagnostics_cleanup_orphan_containers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
        };
    };
    cleanup_dangling_volumes_api_v1_diagnostics_cleanup_dangling_volumes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_v1_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_api_v1_notifications_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_all_api_v1_notifications_read_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    mark_read_api_v1_notifications__notification_id__read_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notification_events_api_v1_notifications_events_get: {
        parameters: {
            query?: {
                after?: number;
                once?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_security_api_v1_security_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityOut"];
                };
            };
        };
    };
    update_security_api_v1_security_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecurityUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setup_status_api_v1_setup_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusOut"];
                };
            };
        };
    };
    run_setup_api_v1_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_v1_system_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemSummaryOut"];
                };
            };
        };
    };
    get_metrics_api_v1_system_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostMetricsOut"];
                };
            };
        };
    };
    get_system_health_api_v1_system_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemHealthOut"];
                };
            };
        };
    };
    get_updates_api_v1_updates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatesOut"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
}
