import type { components } from '@/api/schema'

export type AppAuth = components['schemas']['AppAuthOut']
export type AppAuthSummary = components['schemas']['AppAuthSummary']
export type AppDetail = components['schemas']['AppDetailOut']
export type AppState = components['schemas']['AppStateOut']
export type AuditEvent = components['schemas']['AuditEventOut']
export type Backup = components['schemas']['BackupOut']
export type Config = components['schemas']['ConfigOut']
export type Container = components['schemas']['ContainerOut']
export type Diagnostics = components['schemas']['DiagnosticsOut']
export type Health = components['schemas']['HealthOut']
export type Job = components['schemas']['JobOut']
export type Logs = components['schemas']['LogsOut']
export type LoginRequest = components['schemas']['LoginRequest']
export type Notification = components['schemas']['NotificationOut']
export type NotificationList = components['schemas']['NotificationListOut']
export type Security = components['schemas']['SecurityOut']
export type SystemSummary = components['schemas']['SystemSummaryOut']
export type User = components['schemas']['UserOut']
